server:
  port: 4001
spring:
  application:
    name: mq-consumer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
      bindings:
        testInput:
          destination: test-exchange
          content-type: application/json
          binder: rabbit
