spring:
  application:
    name: boot-dubbo-consumer
dubbo:
  application:
    name: duboo-consumer-service
    id: duboo-consumer-service
  registry:
    address: 8.140.150.213:2181
    protocol: zookeeper
  monitor:
    protocol: registry
server:
  port: 8002